### ISSUE TITLE
Segfault at speed 2 or lower

### ISSUE THREAD

**Issue by utack** [OpenVisualCloud/SVT-AV1#1107]
I currently am getting a segfault at speed lower than 2

Compiling on Arch Linux with default options
> make clean && cmake . && make -j24

Trying to encode  with
>ffmpeg -i input.mkv -pix_fmt yuv420p -f yuv4mpegpipe - | ~/Downloads/SVT-AV1/Bin/Release/SvtAv1EncApp -i stdin -rc 0 -q 34 -intra-period 255 -irefresh-type 2 -enc-mode 0 -b svt.ivf

from 3 tested sources
Results in one frame and a crash

> Encoding         1Segmentation fault (core dumped)

gdb backtrace tells this:

> #0  0x00007ffff734cd79 in set_md_stage_counts () from /home/jakob/Downloads/SVT-AV1/Bin/Release/libSvtAv1Enc.so.0
#1  0x00007ffff7357410 in md_encode_block () from /home/jakob/Downloads/SVT-AV1/Bin/Release/libSvtAv1Enc.so.0
#2  0x00007ffff73594b8 in mode_decision_sb () from /home/jakob/Downloads/SVT-AV1/Bin/Release/libSvtAv1Enc.so.0
#3  0x00007ffff72b1d14 in enc_dec_kernel () from /home/jakob/Downloads/SVT-AV1/Bin/Release/libSvtAv1Enc.so.0
#4  0x00007ffff703d46f in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff6e273d3 in clone () from /usr/lib/libc.so.6

**Comment by utack** [comment]
It may have been from improperly deleted first pass stat files, can't reproduce it any more
