### ISSUE TITLE
Illegal instruction on Xubuntu18.04

### ISSUE THREAD

**Issue by syniox** [OpenVisualCloud/SVT-AV1#316]
(sorry for my bad English)
system: Xubuntu18.04 64bit(Intel SSE),GCC7.4
[commit: 2f4852a](https://github.com/OpenVisualCloud/SVT-AV1/commit/2f4852a031277cfb7cfd2f07c7a4f41c8591fcc7)

It seems that it Crashed at initialization?
I tried to memset config_ptr before settings, but nothing happened.
Thanks for helping.

```
gdb ./SvtAv1EncApp 
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./SvtAv1EncApp...done.
(gdb) r -version
Starting program: /home/suy/Programs/svt-av1/Bin/Debug/SvtAv1EncApp -version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
-------------------------------------------
SVT-AV1 Encoder

Program received signal SIGILL, Illegal instruction.
0x0000555555573641 in eb_config_ctor (config_ptr=0x5555557c9280)
    at /home/suy/Programs/svt-av1/Source/App/EncApp/EbAppConfig.c:478
478	    config_ptr->performance_context.total_execution_time = 0;
(gdb) bt
#0  0x0000555555573641 in eb_config_ctor (config_ptr=0x5555557c9280)
    at /home/suy/Programs/svt-av1/Source/App/EncApp/EbAppConfig.c:478
#1  0x0000555555581813 in main (argc=2, argv=0x7fffffffdf88)
    at /home/suy/Programs/svt-av1/Source/App/EncApp/EbAppMain.c:118
```

**Comment by jbeich** [comment]
Does your CPU support AVX instructions? If not try 5a51cc6f96fe (from #162).

**Comment by syniox** [comment]
PR 418 fixed.
