### ISSUE TITLE
Segfault in decoder calling read_cdef

### ISSUE THREAD

**Issue by tmatth** [OpenVisualCloud/SVT-AV1#358]
This sample (generated by rav1e, see https://github.com/xiph/rav1e/issues/1286) segfaults in read_cdef when dereferencing cdef_strength (which is NULL):
```
Program received signal SIGSEGV, Segmentation fault.
read_cdef (dec_handle=0x55555555c6f0, r=0x555555567250, xd=0x7fffffffcdd0, mi_col=0, mi_row=0, cdef_strength=0x0) at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:538
538	            cdef_strength[3] = -1;
(gdb) bt
#0  read_cdef (dec_handle=0x55555555c6f0, r=0x555555567250, xd=0x7fffffffcdd0, mi_col=0, mi_row=0, cdef_strength=0x0) at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:538
#1  0x00007ffff6410161 in intra_frame_mode_info (dec_handle=0x55555555c6f0, xd=0x7fffffffcdd0, mi_row=0, mi_col=0, r=0x555555567250, cdef_strength=0x0)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:822
#2  0x00007ffff6410d43 in mode_info (decHandle=0x55555555c6f0, part_info=0x7fffffffcdd0, mi_row=0, mi_col=0, r=0x555555567250, cdef_strength=0x0)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:1035
#3  0x00007ffff64161b9 in parse_block (dec_handle=0x55555555c6f0, mi_row=0, mi_col=0, r=0x555555567250, subsize=BLOCK_64X64, tile=0x55555556c944, sb_info=0x555555572950, partition=PARTITION_NONE)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:2682
#4  0x00007ffff641683c in parse_partition (dec_handle=0x55555555c6f0, blk_row=0, blk_col=0, reader=0x555555567250, bsize=BLOCK_64X64, sb_info=0x555555572950)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:2810
#5  0x00007ffff6416e79 in parse_super_block (dec_handle=0x55555555c6f0, blk_row=0, blk_col=0, sbInfo=0x555555572950) at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:2870
#6  0x00007ffff641e26f in parse_tile (bs=0x7fffffffdc30, dec_handle_ptr=0x55555555c6f0, tile_info=0x55555555cda4, tile_row=0, tile_col=0)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseObu.c:2089
#7  0x00007ffff641e805 in read_tile_group_obu (bs=0x7fffffffdc30, dec_handle_ptr=0x55555555c6f0, tiles_info=0x55555555cda4, obu_header=0x7fffffffdc10)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseObu.c:2217
#8  0x00007ffff641eb15 in decode_multiple_obu (dec_handle_ptr=0x55555555c6f0, 
    data=0x7ffff5bb903f "\b\026\247#}E\303\332H\356\n\032\213\367\363\252\312\t\246\017\024\204\201()\347\203&\301X\361\337", <incomplete sequence \337>, data_size=333161)
    at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseObu.c:2315
#9  0x00007ffff6405f5a in eb_svt_decode_frame (svt_dec_component=0x55555555c6d0, data=0x7ffff5bb9010 "\022", data_size=333208) at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecHandle.c:390
#10 0x0000555555555a17 in main (argc=5, argv=0x7fffffffdf18) at /big-repos/SVT-AV1/Source/App/DecApp/EbDecAppMain.c:193
(gdb) frame 0
#0  read_cdef (dec_handle=0x55555555c6f0, r=0x555555567250, xd=0x7fffffffcdd0, mi_col=0, mi_row=0, cdef_strength=0x0) at /big-repos/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:538
538	            cdef_strength[3] = -1;
(gdb) print cdef_strength
$1 = (int8_t *) 0x0
```

[enc_file.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3276838/enc_file.zip)

Note that this file desyncs (see https://bugs.chromium.org/p/aomedia/issues/detail?id=2406 for more context), but dav1d and libaom are able to decode it without crashing.

**Comment by joelsole** [comment]
SVT-AV1 decoder is work in progress. We can make the README more clear. The decoder user guide (https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_decoder_user_guide.md) states the current limitations of the current (initial) version:

Supports only I-frames without loopfilter (deblocking, cdef and self guided restoration filters not supported)
Supports only 8-bit and 10-bit 4:2:0 content
Tested only on Windows

**Comment by joelsole** [comment]
@tmatth , if you have a bitstream with only the features currently supported by the decoder and the decoder is failing with it, please, let us know.

**Comment by tmatth** [comment]
@joelsole yeah I realized after opening this issue. That said, adding warnings or assertions on unimplemented code paths that may crash wouldn't hurt here.

**Comment by joelsole** [comment]
Yes, good suggestion.
