### ISSUE TITLE
Segmentation fault after encoding few frames

### ISSUE THREAD

**Issue by novomesk** [OpenVisualCloud/SVT-AV1#430]
I compiled encoder from sources but the binary seems to crash always after encoding few frames.

```
~/SVT-AV1-0.6.0/Bin/Debug/SvtAv1EncApp -i Susedia.y4m -rc 0 -q 40  -lp 1 -b spadne.ivf                
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :  GCC 8.3.0        64 bit
LIB Build date: Jul  3 2019 12:48:46
-------------------------------------------
Number of logical cores available: 1
Number of PPCS 72
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 720 / 576 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 40 / 33 / 0 
------------------------------------------- 
Encoding       237Chyba segmentácie (bol uložený výpis pamäte)
```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _mm_store_si128 (__B=..., __P=0x7f6003874818) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/emmintrin.h:715
715       *__P = __B;
[Current thread is 1 (Thread 0x7f5fe62d1700 (LWP 13613))]
```

```
#0  _mm_store_si128 (__B=..., __P=0x7f6003874818) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/emmintrin.h:715
#1  aom_paeth_predictor_32x32_ssse3 (
    dst=0x7f6003874818 "he`^_`___^]]\\[ZYYXXWWWWWWVVVVWWWQOLJHHHHEEDEEDCBBBBAAAAAAAA@@@@AABBB", 'A' <repeats 14 times>, "BBBBBBAAAABBBBCCDCDEEGHHKMNNOQSTUVWWY\\^_aba_^^^]^]]\\[[[[\\]^_`abbccdeeeeeedcdccbaaabbbaba```_`___``aaaa`aaaaabaa```````"..., stride=520, 
    above=0x7f5fe62d0330 "da^]_``_]]]]]]^^", ']' <repeats 16 times>, "ssuvvxwwyyyz||||{||||}}}~~~~~\177\177\200\001", 
    left=0x7f5fe62d0290 'd' <repeats 32 times>, 'U' <repeats 32 times>)
    at /home/novomesk/SVT-AV1-0.6.0/Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c:727
#2  0x00007f601fac1320 in build_intra_predictors (xd=xd@entry=0x7f5fe62d0500, 
    topNeighArray=topNeighArray@entry=0x7f5fe62d0cc1 "da^]_``_]]]]]]^^", ']' <repeats 16 times>, "^^]^_befqqqqwwwwsrnjfa]ZWVTTSSRR\200\201\177\200\201\200\201~\206\201_?7CYgTJOQIJMEEDDB:1+,Sdqqkgknicafmrt{\212\221\220\222\222\220\214\202vvzuh`]_\360\237W\300U", leftNeighArray=leftNeighArray@entry=0x7f5fe62d0d51 "", 
    dst=dst@entry=0x7f6003874610 "da^]_``_]]]]]]^^", ']' <repeats 16 times>, "RPMLIHHHEFEEEDDBBBBAAAAAAAA@@@@AABBBAAAAAAAA@@@AAAAAAAAA@@AABBBABAABBBDEFGIJLLMMOQRSTVVXZ]^_]]]\\]^^]\\[[Z[\\]^_``abcccdeeefeeddccc```aabbbaa````````a`aaa```````aa```````_"..., dst_stride=dst_stride@entry=520, mode=mode@entry=PAETH_PRED, angle_delta=0, 
    filter_intra_mode=FILTER_INTRA_MODES, tx_size=TX_32X32, disable_edge_filter=0, n_top_px=32, n_topright_px=32, n_left_px=0, n_bottomleft_px=0, plane=1)
    at /home/novomesk/SVT-AV1-0.6.0/Source/Lib/Common/Codec/EbIntraPrediction.c:3689
#3  0x00007f601fac3829 in av1_predict_intra_block (tile=tile@entry=0x55c0583864e0, stage=stage@entry=1 '\001', blk_geom=0x7f601fd83740 <blk_geom_mds>, 
    cm=0x55c04d75e910, wpx=<optimized out>, hpx=<optimized out>, tx_size=TX_32X32, mode=PAETH_PRED, angle_delta=0, use_palette=0, 
    filter_intra_mode=FILTER_INTRA_MODES, 
    topNeighArray=0x7f5fe62d0cc1 "da^]_``_]]]]]]^^", ']' <repeats 16 times>, "^^]^_befqqqqwwwwsrnjfa]ZWVTTSSRR\200\201\177\200\201\200\201~\206\201_?7CYgTJOQIJMEEDDB:1+,Sdqqkgknicafmrt{\212\221\220\222\222\220\214\202vvzuh`]_\360\237W\300U", leftNeighArray=0x7f5fe62d0d51 "", recon_buffer=0x55c059771280, col_off=0, row_off=0, 
    plane=1, bsize=BLOCK_64X64, tu_org_x_pict=0, tu_org_y_pict=192, bl_org_x_pict=0, bl_org_y_pict=192, bl_org_x_mb=<optimized out>, bl_org_y_mb=<optimized out>)
    at /home/novomesk/SVT-AV1-0.6.0/Source/Lib/Common/Codec/EbIntraPrediction.c:4113
#4  0x00007f601fa81224 in av1_encode_pass (sequence_control_set_ptr=sequence_control_set_ptr@entry=0x55c03d7fdf10, 
    picture_control_set_ptr=picture_control_set_ptr@entry=0x55c0579ff090, sb_ptr=sb_ptr@entry=0x55c0583864b0, tbAddr=tbAddr@entry=36, sb_origin_x=sb_origin_x@entry=0, 
    sb_origin_y=sb_origin_y@entry=192, context_ptr=<optimized out>) at /home/novomesk/SVT-AV1-0.6.0/Source/Lib/Common/Codec/EbCodingLoop.c:2815
#5  0x00007f601fa8b93c in enc_dec_kernel (input_ptr=0x55c059bfbda0) at /home/novomesk/SVT-AV1-0.6.0/Source/Lib/Common/Codec/EbEncDecProcess.c:1604
#6  0x00007f601f996408 in start_thread () at pthread_create.c:486
#7  0x00007f601f78231f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by hassount** [comment]
@novomesk 
Thank you for your report, can you please share with us the content to reproduce this issue

**Comment by novomesk** [comment]
I prepared an example video I am able to reproduce crash with. Same video encodes on Windows correctly (via SvtAv1EncApp.exe), but on Linux I get segmentation fault after few seconds of encoding.
Very shorts video (8 seconds or shorter usually works fine).

Sample video: https://www.dropbox.com/s/22syw0qezokarid/videotest.zip?dl=0 (contains nabielehokona.y4m file)

Crash from another Linux computer:

```
~/SVT-AV1-0.6.0/Bin/Debug/SvtAv1EncApp -i nabielehokona.y4m -rc 0 -q 40 -lp 4 -b test3.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :  GCC 8.3.0        64 bit
LIB Build date: Jul  5 2019 10:03:21
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 72
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 720 / 576 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 40 / 33 / 0 
------------------------------------------- 
Encoding       491Chyba segmentácie
```

**Comment by hassount** [comment]
@novomesk 
From your trace this should be solved by the following commit as part of fixing #84, I have validated this with your test clip on my machine
b9225f06242be2e1dd8e4e918622eb708839384f

Could you please validate that it addressed this issue ?

**Comment by novomesk** [comment]
I will try next week and let you know.

**Comment by novomesk** [comment]
I tried latest version from git and it worked fine:

```
~/SVT-AV1-master/Bin/Release/SvtAv1EncApp -i nabielehokona.y4m -rc 0 -q 40 -lp 8 -b test5.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :  GCC 8.3.0        64 bit
LIB Build date: Jul 17 2019 15:49:25
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 72
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 720 / 576 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 40 / 33 / 0 
------------------------------------------- 
Encoding       750
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         750            25.00 fps                  4671423              1245.71 kbps


Channel 1
Average Speed:          7.380 fps
Total Encoding Time:    101621 ms
Total Execution Time:   101795 ms
Average Latency:        9796 ms
Max Latency:            13052 ms
Encoder finished
```
