### ISSUE TITLE
SvtAv1EncApp crashed for "-scm 1 -enc-mode 5"

### ISSUE THREAD

**Issue by xuguangxin** [OpenVisualCloud/SVT-AV1#605]
commandline： SvtAv1EncApp -i xxx.y4m -scm 1 -enc-mode 5 -b test.bin -n 1
stack:
```
Thread 1 "SvtAv1EncApp" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x34) at malloc.c:3103
3103    malloc.c: No such file or directory.
(gdb) up
#1  0x00005555555f035e in eb_aom_free (memblk=0x7ff8b4000b20) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/EbCdef.c:80
80              free(addr);
(gdb) l
75      void *eb_aom_malloc(size_t size) { return eb_aom_memalign(DEFAULT_ALIGNMENT, size); }
76
77      void eb_aom_free(void *memblk) {
78          if (memblk) {
79              void *addr = GetActualMallocAddress(memblk);
80              free(addr);
81          }
82      }
83
84      void *eb_aom_memset16(void *dest, int32_t val, size_t length) {
(gdb) bt
#0  __GI___libc_free (mem=0x34) at malloc.c:3103
#1  0x00005555555f035e in eb_aom_free (memblk=0x7ff8b4000b20) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/EbCdef.c:80
#2  0x00005555557902ff in hash_table_clear_all (p_hash_table=0x7fff6198a968) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/hash_motion.c:30
#3  0x00005555557905bd in av1_hash_table_destroy (p_hash_table=0x7fff6198a968) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/hash_motion.c:110
#4  0x00005555556bf1f6 in picture_control_set_dctor (p=0x7fff6198a010) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/EbPictureControlSet.c:130
#5  0x0000555555730fd4 in eb_object_wrapper_dctor (p=0x5555979f6d10) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/EbSystemResourceManager.c:419
#6  0x00005555557311dd in eb_system_resource_dctor (p=0x5555979f6c50) at /home/thomas/codec/SVT-AV1/Source/Lib/Common/Codec/EbSystemResourceManager.c:446
#7  0x00005555555defd4 in eb_enc_handle_dctor (p=0x5555614b9a50) at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbEncHandle.c:640
#8  0x00005555555ead77 in eb_h265_enc_component_de_init (svt_enc_component=0x5555614b9a30) at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbEncHandle.c:1825
#9  0x00005555555eaddc in eb_deinit_handle (svt_enc_component=0x5555614b9a30) at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbEncHandle.c:1845
#10 0x00005555555cf04a in de_init_encoder (callback_data_ptr=0x5555614b98d0, instance_index=0) at /home/thomas/codec/SVT-AV1/Source/App/EncApp/EbAppContext.c:641
#11 0x00005555555d13b5 in main (argc=11, argv=0x7fffffffdd78) at /home/thomas/codec/SVT-AV1/Source/App/EncApp/EbAppMain.c:335
(gdb) quit
A debugging session is active.
```

**Comment by xuguangxin** [comment]
this issue found by https://github.com/OpenVisualCloud/SVT-AV1/pull/314#issuecomment-530612742

**Comment by xuguangxin** [comment]
@n808 sorry for missing this. 
I can't reproduce the issue. My command line is
`../Bin/Debug/SvtAv1EncApp -i xxxx.y4m -rc 3 -stat-report 1 -scd 1 -stat-file av1_encode_stats.log -enc-mode 6  -b test.bin -n 1000 -tbr 900000 -nb -1`

could you get the latest code and try your test again?
thanks

**Comment by n808** [comment]
No problem, I have verified that the crash problem has been fixed.
