### ISSUE TITLE
Crash in AVX2 when encoding via FFmpeg

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-AV1#77]
Regressed by #59. Tested on i7-6700K (Skylake) which does have AVX2 support. Lines correspond to a39acb2f2f4a snapshot

```
$ curl -O https://media.xiph.org/video/derf/y4m/bus_cif.y4m
$ ffmpeg -hide_banner -i bus_cif.y4m -c:v libsvt_av1 -y bus_cif.ivf
Input #0, yuv4mpegpipe, from 'bus_cif.y4m':
  Duration: 00:00:05.00, start: 0.000000, bitrate: 36496 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p(progressive), 352x288, SAR 128:117 DAR 1408:1053, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> av1 (libsvt_av1))
Press [q] to stop, [?] for help
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 4.2.1        64 bit
LIB Build date: Feb 21 2019 09:47:00
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 37
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 352 / 288
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 30 / 1 / 12 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 32 / 17 / 0
-------------------------------------------
Output #0, ivf, to 'bus_cif.ivf':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: av1 (libsvt_av1) (AV01 / 0x31305641), yuv420p, 352x288 [SAR 128:117 DAR 1408:1053], q=10-48, 7000 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 libsvt_av1

Thread 44 received signal SIGBUS, Bus error.
[Switching to LWP 101390 of process 23780]
0x00000008060af575 in col_txfm_8x8_rounding (in=0x89426d350, shift=1)
    at Source/Lib/ASM_AVX2/highbd_fwd_txfm_avx2.c:452
452         in[0] = _mm256_add_epi32(in[0], rounding);
(gdb) backtrace full
#0  0x00000008060af575 in col_txfm_8x8_rounding (in=0x89426d350, shift=1)
    at Source/Lib/ASM_AVX2/highbd_fwd_txfm_avx2.c:452
        rounding = {4294967297, 4294967297, 4294967297, 4294967297}
#1  0x00000008060f0278 in av1_fwd_txfm2d_4x16_avx2 (input=0x8942e1c48, output=0x89426d350, stride=128,
    tx_type=DCT_DCT, bd=8 '\b')
    at Source/Lib/ASM_AVX2/highbd_fwd_txfm_avx2.c:5306
        in = {{17179869216, -373662154820, 51539607564, -270582939668}, {-30064771084, -219043332108,
            -30064771076, -98784247828}, {-34359738360, 4294967280, -51539607548, -133143986204}, {-47244640260,
            -219043332124, -167503724568, -150323855388}, {-201863462940, -12884901908, -47244640268,
            -12884901900}, {-81604378636, -47244640264, -98784247820, -64424509452}, {-17179869184,
            -81604378648, -133143986180, -133143986224}, {-253403070480, -253403070532, -253403070492,
            -356482285640}}
        outcoeff256 = 0x89426d350
        shift = 0x805c020f6 <fwd_shift_4x16> "\002\377"
        txw_idx = 0
        txh_idx = 2
        bitcol = 13
        bitrow = 12
#2  0x0000000805d6f738 in Av1EstimateTransform (residual_buffer=0x8942e1c48, residualStride=128,
    coeffBuffer=0x89426d350, coeffStride=0, transform_size=TX_4X16, three_quad_energy=0x8940835b0,
    transform_inner_array_ptr=0x889db5200, bitIncrement=0, transform_type=DCT_DCT, asm_type=ASM_AVX2,
    componentType=PLANE_TYPE_Y, transCoeffShape=0 '\000')
    at Source/Lib/Codec/EbTransforms.c:4619
        row = 0
        return_error = EB_ErrorNone
        bit_depth = 8 '\b'
#3  0x0000000805c810e8 in ProductFullLoopTxSearch (candidateBuffer=0x8930a4160, context_ptr=0x8931bd380,
    picture_control_set_ptr=0x869222000)
    at Source/Lib/Codec/EbFullLoop.c:1214
        shift = 8388736
        txb_itr = 0
        tx_type_index = 0
        tuOriginIndex = 4
        sequence_control_set_ptr = 0x860b21a00
        asm_type = ASM_AVX2
        cleanSparseCoeffFlag = 0 '\000'
        yTuCoeffBits = 0
        tuFullDistortion = {{1189091588869980161, 1}, {140736880031952, 34457524518}, {17179869184, 2139062143}}
        plane = 0
        is_inter = 0
        bestFullCost = 18446744073709551615
        yFullCost = 9223372036854775807
        yCountNonZeroCoeffsTemp = 0
        txk_start = DCT_DCT
        txk_end = TX_TYPES
        tx_type = DCT_DCT
        txb_itr = 0
        txSize = TX_4X16
        tx_set_type = EXT_TX_SET_DTT4_IDTX_1DDCT
        allowed_tx_mask = {1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0}
        allowed_tx_num = 7
        uv_tx_type = DCT_DCT
        best_tx_type = DCT_DCT
#4  0x0000000805d2613f in AV1PerformFullLoop (picture_control_set_ptr=0x869222000, sb_ptr=0x86664ed00,
    cu_ptr=0x893db2848, context_ptr=0x8931bd380, inputPicturePtr=0x870cea020, inputOriginIndex=33256,
    inputCbOriginIndex=8330, cuOriginIndex=4, cuChromaOriginIndex=0, fullCandidateTotalCount=8,
    ref_fast_cost=68806, asm_type=ASM_AVX2)
    at Source/Lib/Codec/EbProductCodingLoop.c:2179
        tx_search_skip_fag = 0 '\000'
        cbQp = 0 '\000'
        crQp = 0 '\000'
        bestfullCost = 4294967295
        fullLoopCandidateIndex = 0
        candidateIndex = 0 '\000'
        y_full_distortion = {0, 0}
        count_non_zero_coeffs = {{5, 33256, 8330, 8330, 2480613448, 8, 1760247312, 4, 0, 9, 3686644780, 32767,
            1892589600, 8, 2383120640, 8, 1, 9, 9, 0, 2383118080}, {8, 4294967295, 4294967295, 1760247744, 8,
            2489073664, 8, 1894233802, 8, 2488770560, 8, 1894174538, 8, 2489057092, 8, 723968, 488, 1893962856,
            8, 2462186144, 8}, {1622284800, 0, 2485515712, 8, 1763844096, 8, 1760247042, 0, 2485515712, 8,
            3686644432, 4294967295, 4294967295, 4294967295, 0, 134217736, 68161540, 0, 114107, 0, 1760247696}}
        cbFullDistortion = {795167925899100160, 220676416100892672}
        crFullDistortion = {36848795460, 549755813888}
        y_coeff_bits = 0
        cb_coeff_bits = 0
        cr_coeff_bits = 0
        candidateBufferPtrArrayBase = 0x88e0b8900
        candidate_buffer_ptr_array = 0x88e0b8900
        candidateBuffer = 0x8930a4160
        candidate_ptr = 0x894260300
#5  0x0000000805d280f3 in md_encode_block (sequence_control_set_ptr=0x860b21a00,
    picture_control_set_ptr=0x869222000, context_ptr=0x8931bd380, ss_mecontext=0x0, leaf_index=4294967295,
    lcuAddr=0, bestCandidateBuffers=0x7fffdbbdbd50)
    at Source/Lib/Codec/EbProductCodingLoop.c:2926
        disable_merge_index = 0 '\000'
        ref_fast_cost = 68806
        sq_index = 0 '\000'
        candidateBufferPtrArrayBase = 0x88e0b8900
        candidate_buffer_ptr_array = 0x88e0b8900
        blk_geom = 0x80623a3fc <blk_geom_mds+8188>
        buffer_total_count = 8
        candidateBuffer = 0xff00010400000001
        fast_candidate_array = 0x89425f5c0
        candidateIndex = 0 '\000'
        fastCandidateTotalCount = 9
        fullCandidateTotalCount = 8
        maxBuffers = 9
        secondFastCostSearchCandidateTotalCount = 9
        asm_type = ASM_AVX2
        best_intra_mode = 4294967295
        inputPicturePtr = 0x870cea020
        inputOriginIndex = 33256
        inputCbOriginIndex = 8330
        cuOriginIndex = 4
        cuChromaOriginIndex = 0
        cu_ptr = 0x893db2848
#6  0x0000000805d28d2f in mode_decision_sb (sequence_control_set_ptr=0x860b21a00,
    picture_control_set_ptr=0x869222000, mdcResultTbPtr=0x86a85fdc0, sb_ptr=0x86664ed00, sb_origin_x=0,
    sb_origin_y=0, lcuAddr=0, ss_mecontext=0x0, context_ptr=0x8931bd380)
    at Source/Lib/Codec/EbProductCodingLoop.c:3223
        blk_geom = 0x80623a3fc <blk_geom_mds+8188>
        cu_ptr = 0x893db2848
        leafDataPtr = 0x86a860134
        return_error = EB_ErrorNone
        cuIdx = 72
        bestCandidateBuffers = {0x8930a4860, 0x800002500000002, 0x8940359a8, 0x8940359a4, 0x8940359a0}
        lastCuIndex = 21
        asm_type = ASM_AVX2
        sb_height = 64
        leaf_count = 4404
        leaf_data_array = 0x86a85fdd4
        blk_idx_mds = 89
        all_d1_blocks_done = 0 '\000'
        d1_blocks_accumlated = 22
#7  0x0000000805c592c5 in EncDecKernel (input_ptr=0x88ffc3800)
    at Source/Lib/Codec/EbEncDecProcess.c:1588
        lcuRow = 0
        context_ptr = 0x88ffc3800
        picture_control_set_ptr = 0x869222000
        sequence_control_set_ptr = 0x860b21a00
        encDecTasksWrapperPtr = 0x87a475780
        encDecTasksPtr = 0x87a449c10
        encDecResultsWrapperPtr = 0x0
        encDecResultsPtr = 0x0
        sb_ptr = 0x86664ed00
        sb_index = 0
        sb_sz = 128 '\200'
        lcuSizeLog2 = 7 '\a'
        xLcuIndex = 0
        yLcuIndex = 0
        sb_origin_x = 0
        sb_origin_y = 0
        lastLcuFlag = 0 '\000'
        endOfRowFlag = 0 '\000'
        lcuRowIndexStart = 0
        lcuRowIndexCount = 0
        picture_width_in_sb = 3
        mdcPtr = 0x86a85fdc0
        is16bit = 0 '\000'
        segment_index = 0
        xLcuStartIndex = 0
        yLcuStartIndex = 0
        lcuStartIndex = 0
        lcuSegmentCount = 3
        lcuSegmentIndex = 0
        segmentRowIndex = 0
        segmentBandIndex = 0
        segmentBandSize = 2
        segmentsPtr = 0x86192c900
#8  0x00000008008e6776 in thread_start (curthread=0x8a334f700) at /usr/src/lib/libthr/thread/thr_create.c:291
        set = {__bits = {0, 0, 0, 0}}
#9  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7fffdbbdc000
```

**Comment by hassount** [comment]
@jbeich 
Thank you for reporting the issue, were you be able to reproduce this crash outside of ffmpeg build ? 
also, this content seems to be quite using with a 3fps refresh rate, would you be able to share this clip with us somehow ?

**Comment by jbeich** [comment]
@hassount, standalone SVT-AV1 doesn't crash while FFmpeg crashes on any sample e.g.,
```
$ ffmpeg -i https://media.xiph.org/ED/ED-1080-png/03150.png -c:v libsvt_av1 -y 03150.ivf
```
