### ISSUE TITLE
AddressSanitizer: stack-use-after-scope (on any input)

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-AV1#79]
Found on FreeBSD with Clang 8.0. Lines correspond to a39acb2f2f4a snapshot

```
$ curl -O https://media.xiph.org/video/derf/y4m/bus_cif.y4m
$ ffmpeg -i bus_cif.y4m -y bus_cif.yuv
$ SvtAv1EncApp -i bus_cif.yuv -w 352 -h 288 -b bus_cif.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 4.2.1        64 bit
LIB Build date: Feb 21 2019 09:37:43
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 37
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 3
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 352 / 288
SVT [config]: FrameRate / Gop Size                                              : 30 / 32
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding          =================================================================
==9869==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fffdcbdead0 at pc 0x00000107ac82 bp 0x7fffdcbdea90 sp 0x7fffdcbde240
WRITE of size 8 at 0x7fffdcbdead0 thread T35
    #0 0x107ac81 in __asan_memset (/usr/local/bin/SvtAv1EncApp+0x59c81)
    #1 0x80172d688 in build_intra_predictors Source/Lib/Codec/EbIntraPrediction.c:8713:17
    #2 0x80172c5c2 in av1_predict_intra_block Source/Lib/Codec/EbIntraPrediction.c:9583:5
    #3 0x80155d96f in AV1EncodePass Source/Lib/Codec/EbCodingLoop.c:3313:37
    #4 0x8015b61d2 in EncDecKernel Source/Lib/Codec/EbEncDecProcess.c:1621:21
    #5 0x8011aa775 in thread_start /usr/src/lib/libthr/thread/thr_create.c:291:16

Address 0x7fffdcbdead0 is located in stack of thread T35 at offset 48 in frame
    #0 0x80172c5ef in build_intra_predictors Source/Lib/Codec/EbIntraPrediction.c:8619

  This frame has 2 object(s):
    [32, 192) 'left_data6' (line 8637) <== Memory access at offset 48 is inside this variable
    [256, 416) 'above_data7' (line 8638)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T35 created by T0 here:
    #0 0x10fcabd in __interceptor_pthread_create (/usr/local/bin/SvtAv1EncApp+0xdbabd)
    #1 0x801a4f488 in EbCreateThread Source/Lib/Codec/EbThreads.c:95:13
    #2 0x8015e96c3 in eb_init_encoder Source/Lib/Codec/EbEncHandle.c:1732:9
    #3 0x113b02e in InitEncoder Source/App/EbAppContext.c:609:20
    #4 0x113f07b in main Source/App/EbAppMain.c:161:52
    #5 0x107311c in _start /usr/src/lib/csu/amd64/crt1.c:76:7
    #6 0x80117dfff  (<unknown module>)

SUMMARY: AddressSanitizer: stack-use-after-scope (/usr/local/bin/SvtAv1EncApp+0x59c81) in __asan_memset
Shadow bytes around the buggy address:
  0x4ffffb97bd00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb97bd10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb97bd20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb97bd30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb97bd40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x4ffffb97bd50: 00 00 00 00 f1 f1 f1 f1 f8 f8[f8]f8 f8 f8 f8 f8
  0x4ffffb97bd60: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2
  0x4ffffb97bd70: f2 f2 f2 f2 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x4ffffb97bd80: f8 f8 f8 f8 f8 f8 f8 f8 f3 f3 f3 f3 f3 f3 f3 f3
  0x4ffffb97bd90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb97bda0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==9869==ABORTING
```

**Comment by jbeich** [comment]
I can't reproduce after #136.
